[platformio]
default_envs = esp32s3
data_dir = build/store
[riscrte]
version = 0.1.0

[env:esp32s3]
platform = espressif32@6.13.0
platform_packages =
  platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
  espressif/toolchain-xtensa-esp32s3@8.4.0+2021r2-patch5
  platformio/tool-esptoolpy@2.41100.260830
framework = arduino
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -DBOARD_HAS_PSRAM
  -DARDUINO_LOOP_STACK_SIZE=16384
  -DCONFIG_ELF_LOADER=1
  -DCONFIG_ELF_DYNAMIC_LOAD_SHARED_OBJECT=1
  -DCONFIG_ELF_LOADER_LOAD_PSRAM=1
  -DCONFIG_ELF_LOADER_BUS_ADDRESS_MIRROR=1
  -DCONFIG_ELF_LOADER_CACHE_OFFSET=1
  -DCONFIG_ELF_LOADER_LIBC_SYMBOLS=1
  -DCONFIG_ELF_FILE_SYSTEM_BASE_PATH=\"/bootfs\"
  -Isdk/driver
  -Isdk/hardware
  -Isdk/app
extra_scripts = pre:scripts/reproducible_build.py
monitor_speed = 115200
