#pragma once
typedef int esp_err_t;
#define ESP_OK 0
#define ESP_FAIL -1
#define ESP_ERR_INVALID_STATE 0x103
#define ESP_ERR_NO_MEM 0x101
#define ESP_ERR_WIFI_NOT_INIT 0x3001
#define ESP_ERR_WIFI_NOT_STARTED 0x3002
#define ESP_ERR_WIFI_NOT_CONNECT 0x300f
#define ESP_ERR_ESP_NETIF_DHCP_ALREADY_STOPPED 0x5004
#define ESP_ERR_ESP_NETIF_IF_NOT_READY 0x5006
